### ISSUE TITLE
Rendering Maldives lags libosmscout and gives a lot font errors

### ISSUE THREAD

**Issue by syyyr** [Framstag/libosmscout#1474]
Hi,

whenever I instruct libosmscout to render an area that includes Maldives (I think it's Maldives?), libosmscout hangs and prints a bunch of errors in this format:
```
OpenType support missing for "", script 10
```
libosmscout prints a lot of these and some also include a font name like this:
```
OpenType support missing for "Noto Sans", script 10
```
After a while (a few seconds), the rendered map evcevntually shows up and looks like this:
![image](https://github.com/Framstag/libosmscout/assets/17759291/902c2f62-16ac-4781-a009-c80ecfd9d4c6)

I'm not sure how to deal with this. I guess Maldives' language uses some script that's not supported by any of my fonts? I have a few solutions, but I'm not sure how to implement them:
1) Somehow instruct libosmscout to not render stuff that's not in the latin alphabet - I realize this is probably not possible in libosmcout.
2) Limit the number of fonts that libosmscout tries before giving up on rendering the text. This is maybe dependent on what kind of font library libosmscout uses?
3) Instruct libosmscout to prefer English when rendering - this would be a great solution, but I'd like to choose which language is used for what. For example, for Czechia, I'd like it to use Czech, and only for others, I'd like it to use English.
4) Just filter out Maldives - of course, I don't really need Maldives and other countries in my data, so if nothing can be done in libosmscout, I'd be ok to fallback to this option.

What do you think?

Thanks

**Comment by Karry** [comment]
Ahoj Vašku. 

ad 1) I would not prefer that.
ad 2) Yes, it sounds reasonable. But I have no idea howto detect the case when font is unable to render text. What backend you are using? Qt?
ad 3) It is possible already - partially. Libosmscout imports names from OSM tag "name" that contains local name, and it also imports one alternative language (name:<lang>). English is used usually, but it may be specified during import. During rendering, you may instruct renderer to use alternative language when available.

**Comment by Framstag** [comment]
I agree with the responses of @Karry . IMHO this is not a problem of libosmscout itself but the OS rendering -e specially the font rendering - engine. AFAIK you do not have a front file with information for all languages support all unicode, but you only have a font file for parts of unicode range. The font engine thus has to load some font files to get the requested unicode characters covered. This might fail, if the engine is mis-configured or font files are just not installed. libosmscout just needs enough API to enable passing such information to the low level font engine. Under Linux I assume that you do not have to pass anything at all, since such configuration is likely be done on the OS level itself. I would first check what you need to install on the iPhone/Mac to get font rendering in such languages supported in principle. I assume this will contain additional font files.

If this is not helpful, we would have to check, how we can drop "native rendering" of some languages. E.g., by falling back to english names. The problems here are:
- libosmscout does not know anything about supported characters. We would have to look for APIs to query that and this may be a huge query since we are rendering "the world".
- libosmscout also does not know anything about the geographical region and language of a label (if not tagged explicitly). There is no way to say "for India please render..." during runtime since "for India" is something that libosmscout does not know. So such things would have to be done during import time by splitting regions in individual databases and by individual import options for such regions. If not already possible this should be easier to add.

**Comment by Framstag** [comment]
It is also possible that the specific font you configured for rendering is not capable enough and you just have to switch to another font.

**Comment by Framstag** [comment]
I did test with Qt5+Linux for Maldives and did not get such errors. I did see however, some coastline errors. I cannot judge if the rendering is correct but I did see looks-like-native and englisch labels.

**Comment by syyyr** [comment]
- I haven't tried Qt5, it is possible that my issue is Qt6 specific. I'll try it on Qt5 also.
- I will try other fonts, but it seems to me that the font engine does try alternatives and it just can't find any (which is weird and also I don't know why it takes so long)

In the end, it'll probably the best for me to just use the English names. Names of countries in native language doesn't really help me. Or maybe I'll just filter out the problematic stuff and be done with it.

Either way, thanks for the answers, I'll try your suggestions on Monday.

**Comment by syyyr** [comment]
Hi, sorry, I still haven't had the chance to look at this. I'll get back to you as soon as I have something.

**Comment by syyyr** [comment]
I have looked into this a bit more and unfortunately I wasn't really able to figure it out. It seems that this thread has the same issue: https://forum.qt.io/topic/141464/qfontdatabase-slowing-down-my-application-with-flood-of-opentype-support-missing-warnings h

I was also able to get a backtrace:
```
#0  QFontDatabasePrivate::loadSingleEngine(int, QFontDef const&, QtFontFamily*, QtFontFoundry*, QtFontStyle*, QtFontSize*) (script=10, script@entry=2, request=..., family=family@entry=0x555555e87950, foundry=0x555555e87a90, style=style@entry=0x555555f05d20, size=0x555555c72770) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/gui/text/qfontdatabase.cpp:705
#1  0x00007ffff6bc3b49 in QFontDatabasePrivate::loadEngine(int, QFontDef const&, QtFontFamily*, QtFontFoundry*, QtFontStyle*, QtFontSize*) (script=2, request=..., family=0x555555e87950, foundry=<optimized out>, style=0x555555f05d20, size=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/gui/text/qfontdatabase.cpp:785
#2  0x00007ffff6bce8d2 in QFontDatabasePrivate::findFont(QFontDef const&, int, bool) (req=..., script=script@entry=2, preferScriptOverFamily=preferScriptOverFamily@entry=false) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/gui/text/qfontdatabase.cpp:2473
#3  0x00007ffff6bcf186 in QFontDatabasePrivate::load(QFontPrivate const*, int) (d=<optimized out>, script=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/gui/text/qfontdatabase.cpp:2560
#4  0x00007ffff6e8960a in QFontPrivate::engineForScript(int) const [clone .constprop.0] (this=0x7fffb42e5a10, script=2) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/gui/text/qfont.cpp:250
#5  0x00007ffff6bd5080 in QFontMetrics::leading() const (this=this@entry=0x7fffd1bf9868) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/gui/text/qfontmetrics.cpp:307
#6  0x00007ffff7f18443 in osmscout::MapPainterQt::Layout(osmscout::Projection const&, osmscout::MapParameter const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double, double, bool, bool)
    (this=0x7fffb42c6c90, projection=..., parameter=..., text="Монгол Улс", fontSize=3, objectWidth=objectWidth@entry=0, enableWrapping=enableWrapping@entry=true) at ../libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp:414
#7  0x00007ffff7f2496d in osmscout::LabelLayouter<QGlyphRun, QTextLayout, osmscout::MapPainterQt>::ProcessLabel(osmscout::Projection const&, osmscout::MapParameter const&, osmscout::Vertex2D const&, osmscout::LabelInstance<QGlyphRun, QTextLayout>&, double&, osmscout::LabelData const&, double)
    (this=this@entry=0x7fffb42c6fa0, projection=..., parameter=..., point=..., instance=..., offset=@0x7fffd1bf9a68: -1, data=..., objectWidth=objectWidth@entry=0) at ../libosmscout-map/include/osmscoutmap/LabelLayouter.h:738
#8  0x00007ffff7f1a5e5 in osmscout::LabelLayouter<QGlyphRun, QTextLayout, osmscout::MapPainterQt>::RegisterLabel(osmscout::Projection const&, osmscout::MapParameter const&, osmscout::Vertex2D const&, std::vector<osmscout::LabelData, std::allocator<osmscout::LabelData> > const&, double)
    (objectWidth=0, data=<optimized out>, point=..., parameter=..., projection=..., this=0x7fffb42c6fa0) at ../libosmscout-map/include/osmscoutmap/LabelLayouter.h:785
#9  osmscout::MapPainterQt::RegisterRegularLabel(osmscout::Projection const&, osmscout::MapParameter const&, std::vector<osmscout::LabelData, std::allocator<osmscout::LabelData> > const&, osmscout::Vertex2D const&, double) (this=<optimized out>, projection=..., parameter=..., labels=<optimized out>, position=..., objectWidth=0)
    at ../libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp:878
#10 0x00007ffff716e7c1 in osmscout::MapPainter::LayoutPointLabels(osmscout::Projection const&, osmscout::MapParameter const&, osmscout::FeatureValueBuffer const&, std::shared_ptr<osmscout::IconStyle> const&, std::vector<std::shared_ptr<osmscout::TextStyle>, std::allocator<std::shared_ptr<osmscout::TextStyle> > > const&, osmscout::Vertex2D const&, osmscout::ScreenBox const&)
    (this=this@entry=0x7fffb42c6c90, projection=..., parameter=..., buffer=<optimized out>, iconStyle=std::shared_ptr<osmscout::IconStyle> (empty) = {...}, textStyles=std::vector of length 1, capacity 4 = {...}, screenPos=..., objectBox=...) at ../libosmscout-map/src/osmscoutmap/MapPainter.cpp:461
#11 0x00007ffff716f093 in osmscout::MapPainter::PrepareNode(osmscout::StyleConfig const&, osmscout::Projection const&, osmscout::MapParameter const&, std::shared_ptr<osmscout::Node> const&) (this=this@entry=0x7fffb42c6c90, styleConfig=..., projection=..., parameter=..., node=std::shared_ptr<osmscout::Node> (use count 4, weak count 0) = {...})
    at ../libosmscout/include/osmscout/Node.h:112
#12 0x00007ffff716f120 in osmscout::MapPainter::PrepareNodes(osmscout::StyleConfig const&, osmscout::Projection const&, osmscout::MapParameter const&, osmscout::MapData const&) (this=this@entry=0x7fffb42c6c90, styleConfig=..., projection=..., parameter=..., data=...) at ../libosmscout-map/src/osmscoutmap/MapPainter.cpp:502
#13 0x00007ffff7171dab in osmscout::MapPainter::PrepareNodeLabels(osmscout::Projection const&, osmscout::MapParameter const&, osmscout::MapData const&) (this=0x7fffb42c6c90, projection=..., parameter=..., data=...) at /usr/include/c++/13.2.1/bits/shared_ptr_base.h:1665
#14 0x00007ffff7166718 in osmscout::MapPainter::Draw(osmscout::Projection const&, osmscout::MapParameter const&, osmscout::MapData const&, osmscout::RenderSteps, osmscout::RenderSteps) (endStep=<optimized out>, startStep=<optimized out>, data=<optimized out>, parameter=<optimized out>, projection=<optimized out>, this=<optimized out>)
    at ../libosmscout-map/src/osmscoutmap/MapPainter.cpp:1899
#15 osmscout::MapPainter::Draw(osmscout::Projection const&, osmscout::MapParameter const&, osmscout::MapData const&, osmscout::RenderSteps, osmscout::RenderSteps) (this=this@entry=0x7fffb42c6c90, projection=..., parameter=..., data=..., startStep=startStep@entry=osmscout::PrepareNodeLabels, endStep=endStep@entry=osmscout::PrepareNodeLabels)
    at ../libosmscout-map/src/osmscoutmap/MapPainter.cpp:1884
#16 0x00007ffff7f1896d in osmscout::BatchMapPainterQt::paint(osmscout::Projection const&, osmscout::MapParameter const&, QPainter*) (this=this@entry=0x7fffd1bfa010, projection=..., parameter=..., qPainter=<optimized out>) at ../libosmscout-map-qt/src/osmscoutmapqt/MapPainterQt.cpp:1141
#17 0x00007ffff7dc3e91 in osmscout::DBRenderJob::Run(std::shared_ptr<osmscout::BasemapDatabase> const&, std::__cxx11::list<std::shared_ptr<osmscout::DBInstance>, std::allocator<std::shared_ptr<osmscout::DBInstance> > > const&, QReadLocker*) (this=0x7fffd1bfa3a0, basemapDatabase=<optimized out>, allDatabases=<optimized out>, locker=<optimized out>)
    at ../libosmscout-client-qt/src/osmscoutclientqt/MapRenderer.cpp:359
#18 0x00007ffff7dc91a0 in osmscout::PlaneMapRenderer::DrawMap() (this=<optimized out>) at /usr/include/c++/13.2.1/bits/shared_ptr_base.h:1665
#19 0x00007ffff737d147 in QObject::event(QEvent*) (this=0x555555765960, e=0x7fffb40371e0) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qobject.cpp:1391
#20 0x00007ffff733b718 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x555555765960, event=event@entry=0x7fffb40371e0) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qcoreapplication.cpp:1118
#21 0x00007ffff733ba9b in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7fffb40371e0, receiver=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qcoreapplication.cpp:1536
#22 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x5555555b0e70) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qcoreapplication.cpp:1898
#23 0x00007ffff7534854 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=0x0, event_type=0) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qcoreapplication.cpp:1757
#24 postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x7fffb4000f10) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qeventdispatcher_glib.cpp:243
#25 0x00007ffff610fa31 in g_main_dispatch (context=0x7fffb4000c60) at ../glib/glib/gmain.c:3460
#26 g_main_context_dispatch (context=0x7fffb4000c60) at ../glib/glib/gmain.c:4200
#27 0x00007ffff616ccc9 in g_main_context_iterate.isra.0 (context=context@entry=0x7fffb4000c60, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4276
#28 0x00007ffff610d0e2 in g_main_context_iteration (context=0x7fffb4000c60, may_block=1) at ../glib/glib/gmain.c:4343
#29 0x00007ffff7532794 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffb4000b70, flags=...) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qeventdispatcher_glib.cpp:393
#30 0x00007ffff7345623 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (flags=..., this=0x7fffd1bfab90) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qeventloop.cpp:100
#31 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffd1bfab90, flags=...) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qeventloop.cpp:182
#32 0x00007ffff742d24f in QThread::exec() (this=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/thread/qthread.cpp:578
#33 QThread::run() (this=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/thread/qthread.cpp:699
#34 0x00007ffff7473352 in operator() (__closure=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/thread/qthread_unix.cpp:321
#35 (anonymous namespace)::terminate_on_exception<QThreadPrivate::start(void*)::<lambda()> > (t=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/thread/qthread_unix.cpp:257
#36 QThreadPrivate::start(void*) (arg=0x5555557a5cb0) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/thread/qthread_unix.cpp:280
#37 0x00007ffff5a8c9eb in start_thread (arg=<optimized out>) at pthread_create.c:444
#38 0x00007ffff5b1123c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```
It seems that the issue appears when Qt is trying to find a font for `Script_Thaana`, which is the language for Maldives. My terminal *seems* to render the text properly, so I guess this is a Qt bug rather than a libosmscout bug.

I have no idea how to deal with this, so I think my only option is to try to filter the OSM data, so that it doesn't include the native language stuff (which isn't very useful to me anyway).

As I said, this bug is probably not libosmscout related, so I'm closing this issue.

**Comment by syyyr** [comment]
Some more info: it looks my bug really only appears in Qt6. With Qt5, OSMScout2 works fine with Maldives.
