### ISSUE TITLE
free(): invalid pointer: 0x442c4410 in osmscout::LabelLayouter::DeleteEventsForLabel

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#207]
Hi Tim. I have luck today. When I was playing with OSMScout on phone, it crashed. Luckily, it remember map position, so this crash is reproducible with specific map and configuration. Here is stacktrace from gdb:
```
#0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
#1  0x40d6ad2e in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0x40d6dbb4 in __GI_abort () at abort.c:89
#3  0x40d939f8 in __libc_message (do_abort=<optimized out>, fmt=0x40e25c58 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#4  0x40d9c6fe in malloc_printerr (ptr=<optimized out>, str=0x40e25d8c "free(): invalid pointer", action=1) at malloc.c:4996
#5  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#6  0x40d9eb3e in __GI___libc_free (mem=<optimized out>) at malloc.c:2946
#7  0x00145b86 in deallocate (this=<optimized out>, __p=<optimized out>) at /opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/ext/new_allocator.h:110
#8  _M_put_node (this=<optimized out>, __p=<optimized out>) at /opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/bits/stl_tree.h:374
#9  _M_destroy_node (this=<optimized out>, __p=<optimized out>) at /opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/bits/stl_tree.h:422
#10 _M_erase_aux (__position=..., this=0x442c440c) at /opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/bits/stl_tree.h:1746
#11 erase (__position=..., this=0x442c440c) at /opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/bits/stl_tree.h:809
#12 erase (__position=..., this=0x442c440c) at /opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/bits/stl_set.h:552
Python Exception <class 'gdb.error'> No type named const std::set<osmscout::LabelEvent, std::less<osmscout::LabelEvent>, std::allocator<osmscout::LabelEvent> >::iterator &::_Link_type.: 
#13 osmscout::LabelLayouter::DeleteEventsForLabel (this=this@entry=0x442c4400, eventRef=) at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-map/src/osmscout/LabelLayouter.cpp:70
Python Exception <type 'exceptions.IndexError'> list index out of range: 
#14 0x00146016 in osmscout::LabelLayouter::Placelabel (this=0x442c4400, label=..., labelRef=) at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-map/src/osmscout/LabelLayouter.cpp:235
#15 0x00110ac8 in osmscout::MapPainter::RegisterPointLabel (this=this@entry=0x442c43d0, data=..., x=<optimized out>, y=<optimized out>, id=id@entry=37)
    at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-map/src/osmscout/MapPainter.cpp:846
#16 0x001110c0 in osmscout::MapPainter::LayoutPointLabels (this=this@entry=0x442c43d0, projection=..., parameter=..., buffer=..., iconStyle=std::shared_ptr (empty) 0x0, textStyles=std::vector of length 1, capacity 4 = {...}, 
    x=1289.3175901868331, y=<optimized out>, objectHeight=0) at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-map/src/osmscout/MapPainter.cpp:1018
#17 0x00111f5c in osmscout::MapPainter::DrawNode (this=0x442c43d0, styleConfig=..., projection=..., parameter=..., node=std::shared_ptr (count 2, weak 0) 0x573010)
    at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-map/src/osmscout/MapPainter.cpp:1281
#18 0x0010b806 in osmscout::MapPainter::DrawNodes (this=0x442c43d0, styleConfig=..., projection=..., parameter=..., data=...)
    at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-map/src/osmscout/MapPainter.cpp:1057
#19 0x0011196c in osmscout::MapPainter::Draw (this=0x442c43d0, projection=..., parameter=..., data=...) at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-map/src/osmscout/MapPainter.cpp:2116
#20 0x00105300 in osmscout::MapPainterQt::DrawMap (this=0x442c43d0, projection=..., parameter=..., data=..., painter=0x459df96c)
    at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-map-qt/src/osmscout/MapPainterQt.cpp:1095
#21 0x000e7ed2 in TiledDBThread::DrawMap (this=this@entry=0x280670, p=..., center=..., z=z@entry=13, width=width@entry=1168, height=height@entry=1752, lookupWidth=lookupWidth@entry=1752, lookupHeight=2336)
    at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-client-qt/src/osmscout/TiledDBThread.cpp:257
#22 0x000e9ec6 in TiledDBThread::offlineTileRequest (this=0x280670, zoomLevel=13, xtile=4422, ytile=2769)
    at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-client-qt/src/osmscout/TiledDBThread.cpp:602
#23 0x000fbd30 in TiledDBThread::qt_static_metacall (_o=0x280670, _c=<optimized out>, _id=<optimized out>, _a=0x44db95d8)
    at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/rpmbuilddir-arm/dependencies/libosmscout/libosmscout-client-qt/moc_TiledDBThread.cpp:131
#24 0x401b3436 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#25 0x40197552 in QCoreApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#26 0x40197336 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#27 0x40198fa4 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#28 0x401cbfc8 in ?? () from /usr/lib/libQt5Core.so.5
#29 0x401cbfc8 in ?? () from /usr/lib/libQt5Core.so.5
```

I compile it again with `-DLABEL_LAYOUTER_DEBUG` and it crashed few lines before:
```
#0  operator<< <char, std::char_traits<char>, std::allocator<char> > (__str=<error reading variable: Cannot access memory at address 0x60>, __os=...) at /opt/cross/armv7hl-meego-linux-gnueabi/include/c++/4.8.3/bits/basic_string.h:2758
Python Exception <class 'gdb.error'> No type named const std::set<osmscout::LabelEvent, std::less<osmscout::LabelEvent>, std::allocator<osmscout::LabelEvent> >::iterator &::_Link_type.: 
#1  osmscout::LabelLayouter::DeleteEventsForLabel (this=this@entry=0x442c4400, eventRef=) at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-map/src/osmscout/LabelLayouter.cpp:65
Python Exception <type 'exceptions.IndexError'> list index out of range: 
#2  0x001465b0 in osmscout::LabelLayouter::Placelabel (this=0x442c4400, label=..., labelRef=) at /home/mersdk/share/SailfishOS/projects/osmscout-sailfish/dependencies/libosmscout/libosmscout-map/src/osmscout/LabelLayouter.cpp:235
```

It seems that `assert(event!=events.end());` was removed by compiler and event is invalid iterator... What can be wrong here?

**Comment by Framstag** [comment]
Does not look like I'm lucky ;-) It is my code that is crashing :_|=|

The label layouter uses a set of label events to mark the begin and the end of a label (vertically). Labels events are thus first sorted by the y coordinate. It uses a sweep line technique (https://en.wikipedia.org/wiki/Line_segment_intersection) to optimize the search for intersection rectangles. During the work of the algorithm it is possible that rectangles get removed. In this case the both entries (top and bottom) must be removed. It looks like there is still a bug in it. Though it find one entry it doe snot seem to find the other one. I could only image that *before* that the wrong entry was deleted. This could possibly happen if two labels have the same x/y coordinate for the top or bottom. Can you check this.

I did change the operator< for LabelEvent to the following as a possible quick fix:

```
    inline bool operator<(const LabelEvent& other) const
    {
      if (y!=other.y) {
        return y<other.y;
      }

      if (x!=other.x) {
        return x<other.x;
      }

      return label->id<other.label->id;
    }
```

But this lead to a crash on my system. I have to look a this to see why this is happening.

You are likely building with debug switched off, this will remove all assertions.

**Comment by Framstag** [comment]
Hmm my crash is the following:

```
Thread 9 "QThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc3ddd700 (LWP 23068)]
0x00007ffff7b780d8 in PlaneDBThread::DrawMap (this=0x743100)
    at osmscout/PlaneDBThread.cpp:404
404	                      QBrush(QColor::fromRgbF(finishedUnknownFillStyle->GetFillColor().GetR(),
(gdb) bt
#0  0x00007ffff7b780d8 in PlaneDBThread::DrawMap() (this=0x743100)
    at osmscout/PlaneDBThread.cpp:404
#1  0x00007ffff494e0c9 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/libQt5Core.so.5
#2  0x00007ffff495b148 in QTimer::timerEvent(QTimerEvent*) ()
    at /usr/lib/libQt5Core.so.5
#3  0x00007ffff494eee3 in QObject::event(QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff492277a in QCoreApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff49228e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff497625e in QTimerInfoList::activateTimers() ()
    at /usr/lib/libQt5Core.so.5
#7  0x00007ffff4976781 in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff1460587 in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff14607f0 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff146089c in g_main_context_iteration ()
    at /usr/lib/libglib-2.0.so.0
#11 0x00007ffff49772bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#12 0x00007ffff4920d3a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#13 0x00007ffff4743063 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#14 0x00007ffff4747cf8 in  () at /usr/lib/libQt5Core.so.5
#15 0x00007ffff4485454 in start_thread () at /usr/lib/libpthread.so.0
#16 0x00007ffff34857df in clone () at /usr/lib/libc.so.6
```

Is it possible that you recently broke something :-)?

**Comment by Karry** [comment]
I added some debug messages:
```
--- a/libosmscout-map/src/osmscout/LabelLayouter.cpp
+++ b/libosmscout-map/src/osmscout/LabelLayouter.cpp
@@ -59,6 +59,14 @@ namespace osmscout {
     event=events.find(searchEventTop);
 
     assert(event!=events.end());
+    if (event==events.end()){
+      std::cout << "Invalid interator!" << std::endl;
+      std::cout << " searchEventTop x: " << searchEventTop.x << " \t y: " << searchEventTop.y << std::endl;
+      for (const auto &e: events){
+        std::cout << "   x: " << e.x << " \t y: " << e.y << " \t " << e.label->text << std::endl;
+      }
+      return;
+    }
 
 #if defined(LABEL_LAYOUTER_DEBUG)
     std::cout << "Removing event: ";
```

here is full log: https://gist.github.com/Karry/2f683f11dd12af56ac2c3609e1b8d748

**Comment by Karry** [comment]
:-) I create MR for your crash: https://github.com/Framstag/libosmscout/pull/208

**Comment by Karry** [comment]
Problem is that two events with same label id are located on same coordinates:
```
--- Placing: 'Kopeč' 1285.22 - 1325.22, 236.635 - 253.635
Event: 'Kopeč' 1285.22,236.635 | 1285.22 - 1325.22, 236.635 - 253.635 | 36
Event: 'Kopeč' 1285.22,253.635 | 1285.22 - 1325.22, 236.635 - 253.635 | 36
--- Placing: '224m' 1285.22 - 1325.22, 253.635 - 270.635
Event: '224m' 1285.22,270.635 | 1285.22 - 1325.22, 253.635 - 270.635 | 36
```
top,left event for second label ('224m') is missing! So, invalid iterator is expected here...

**Comment by Karry** [comment]
Thank you for hint. We just have to compare more fields... This MR finalise the fix: https://github.com/Framstag/libosmscout/pull/209
