### ISSUE TITLE
MergeAreaDataGenerator: Japan and Canada failed on import 

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#239]
I have run importer on a planet and two countries failed to import: Japan and Canada. Error was at the same step: 
```
Step #8 - MergeAreaDataGenerator...
```

Since Japan is smaller, let's start with Japan. Error message was:

```
   13548511 raw way(s) read, 5761741 areas(s) written
   13548511 raw way(s) read, 5761741 areas(s) written
   => 68.003s, RSS 378.7 MiB, VM 2.5 GiB
+ Step #8 - MergeAreaDataGenerator...
   Module description: Merge relation and way area data files into one area file
   Module requires file 'wayarea.tmp'
   Module requires file 'relarea.tmp'
   Module provides temporary file 'areas.tmp'
 - Copying areas from file 'wayarea.tmp'...
   % 49.36 (2843748/5761741)
 - Copying areas from file 'relarea.tmp'...
   % 0.16 (39/24394)
   % 0.66 (160/24394)
   % 1.51 (368/24394)
   % 1.99 (485/24394)
   % 3.89 (948/24394)
   % 4.24 (1034/24394)
   % 6.35 (1550/24394)
   % 7.24 (1766/24394)
   % 7.36 (1796/24394)
   % 8.34 (2035/24394)
   % 9.20 (2244/24394)
   % 10.33 (2519/24394)
   % 17.14 (4180/24394)
   % 19.50 (4758/24394)
   % 26.19 (6388/24394)
   % 26.54 (6475/24394)
   % 29.95 (7307/24394)
   % 42.73 (10423/24394)
   % 42.81 (10444/24394)
   % 43.45 (10598/24394)
   % 47.18 (11509/24394)
   % 50.61 (12347/24394)
   % 51.13 (12472/24394)
   % 52.89 (12901/24394)
   % 52.91 (12908/24394)
   % 52.93 (12911/24394)
   % 56.05 (13673/24394)
   % 57.02 (13909/24394)
   % 57.55 (14039/24394)
   % 57.70 (14075/24394)
   % 58.06 (14164/24394)
   % 58.11 (14176/24394)
   % 58.27 (14215/24394)
   % 58.80 (14343/24394)
   % 59.05 (14405/24394)
   % 59.06 (14407/24394)
   % 59.30 (14465/24394)
   % 59.43 (14498/24394)
   % 59.71 (14566/24394)
   % 61.17 (14921/24394)
   % 64.98 (15851/24394)
   % 66.23 (16156/24394)
   % 66.45 (16211/24394)
   % 66.74 (16281/24394)
   % 66.75 (16284/24394)
   % 67.68 (16509/24394)
   % 67.78 (16534/24394)
   % 72.33 (17645/24394)
   % 72.36 (17651/24394)
   % 93.10 (22710/24394)
   !! File 'full/world/asia/japan/relarea.tmp' - Cannot read byte array: Success
Automatically closing FileScanner for file 'full/world/asia/japan/relarea.tmp'!
   => 320.694s, RSS 570.6 MiB, VM 2.7 GiB
   !! Error while executing step 'MergeAreaDataGenerator'!
+ Summary...
   !! Import failed!
```

I tested it several times and its failing every time. About a week ago, all worked nicely.

**Comment by Karry** [comment]
:-D I am affected with the same (probably) bug. Night build of Great Britain crashed on my computer. It seems that written format of Area is different that is expected on write... I just added asserts https://github.com/karry-space-with-my-second-forks/libosmscout/tree/import-crashes , and will debug it later...

**Comment by Karry** [comment]
Here is stacktrace of my crash:
```
#0  0x00007ffff74ab9c8 in std::__shared_ptr<osmscout::TypeInfo, (__gnu_cxx::_Lock_policy)2>::operator bool (this=0x8) at /usr/include/c++/6/bits/shared_ptr_base.h:1066
#1  0x00007ffff755f664 in osmscout::FeatureValueBuffer::Set (this=0x0, other=...) at /home/karry/data/cecko/OSM/libosmscout/libosmscout/src/osmscout/TypeConfig.cpp:165
#2  0x00007ffff7561339 in osmscout::FeatureValueBuffer::operator= (this=0x0, other=...) at /home/karry/data/cecko/OSM/libosmscout/libosmscout/src/osmscout/TypeConfig.cpp:515
#3  0x00007ffff74a6f12 in osmscout::Area::ReadImport (this=0x7fffffffc500, typeConfig=..., scanner=...) at /home/karry/data/cecko/OSM/libosmscout/libosmscout/src/osmscout/Area.cpp:267
#4  0x00007ffff7a9627c in osmscout::MergeAreaDataGenerator::MergeAreas (this=0x5555557814c0, parameter=..., progress=..., typeConfig=...) at /home/karry/data/cecko/OSM/libosmscout/libosmscout-import/src/osmscout/import/MergeAreaData.cpp:110
#5  0x00007ffff7a968fb in osmscout::MergeAreaDataGenerator::Import (this=0x5555557814c0, typeConfig=std::shared_ptr (count 2, weak 0) 0x55555578f610, parameter=..., progress=...)
    at /home/karry/data/cecko/OSM/libosmscout/libosmscout-import/src/osmscout/import/MergeAreaData.cpp:145
#6  0x00007ffff7a68607 in osmscout::Importer::ExecuteModules (this=0x7fffffffd770, typeConfig=std::shared_ptr (count 2, weak 0) 0x55555578f610, progress=...)
    at /home/karry/data/cecko/OSM/libosmscout/libosmscout-import/src/osmscout/import/Import.cpp:934
#7  0x00007ffff7a69b70 in osmscout::Importer::Import (this=0x7fffffffd770, progress=...) at /home/karry/data/cecko/OSM/libosmscout/libosmscout-import/src/osmscout/import/Import.cpp:1037
#8  0x0000555555563e22 in main (argc=16, argv=0x7fffffffda88) at /home/karry/data/cecko/OSM/libosmscout/Import/src/Import.cpp:937
```

**Comment by rinigus** [comment]
That's odd - Great Britain imported fine for me... But let's hope it the same one!

**Comment by Framstag** [comment]
For great-britain the problematic object is relation 6038068. It has the following rings with the given sizes:
 * 0
 * 70 
 * 645290

The last ring size is >19 bit (22 if I counted correctly). So assume there is some bug in the code by Vladimir. The Merge step crashes while reading the relation that follows the one above. I assume the reading code at that time is not in sync with the actual data anymore and thus starts to read garbage.

Now lets stare at some bit shifting code :-) Let's see, who sees the problem first...

**Comment by Framstag** [comment]
Yes, I extended the FileScannerWriter tests and it shows that storing 645290 points results in an error. Hmmm...

**Comment by Framstag** [comment]
I think, I have found the problem. I'm doing a few more imports to check for new problems before committing.

**Comment by Framstag** [comment]
Pushed, please check (and close the issue).

**Comment by rinigus** [comment]
Pulling, will check ASAP

**Comment by Karry** [comment]
I review write method too and ended up with (logically) same changes... Import of Great Britain ended successfully now. Thank you Tim for adding test :-) I hope that Rinigus error is caused by same bug.

**Comment by rinigus** [comment]
Japan and Canada imported as well. Thank you very much for fixing this! Closing an issue, as suggested.
