### ISSUE TITLE
OSMScout crash on resize

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#326]
Hi, im at e7305f5 on win10 using msys2 mingw 64bit build with qt5.8

When resizing the OSMScout2 window through the corners (width and height at the same time) i pretty reliably get a crash. Funny enough i dont get it when just resising through the edges (width OR height alone).

I also get this behaviour in an older version from February with qt5.6.

Im also not sure if this is a libosmscout bug or a qml bug. I removed the Map qml entry from main.qml and still get the same problem.

Can anyone please verify this behaviour on some other os and optimally on a windows build too?

Its pretty much like described here: 
http://www.qtcentre.org/threads/66045-QGLWidget-crashes-program-when-the-window-is-resized-rapidly

This is the backtrace which also implies something is wrong with OpenGL
```
Thread 14 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 10128.0x292c]
0x0000000043a6322b in atio6axx!DllMain ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
(gdb) bt
#0  0x0000000043a6322b in atio6axx!DllMain ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
#1  0x000000004458c1df in atio6axx!DrvPresentBuffers ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
#2  0x0000000044539e31 in atio6axx!DrvPresentBuffers ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
#3  0x00000000445386c2 in atio6axx!DrvPresentBuffers ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
#4  0x00000000444d74b2 in atio6axx!DrvPresentBuffers ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
#5  0x00000000444c0314 in atio6axx!DrvPresentBuffers ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
#6  0x00000000444c081a in atio6axx!DrvPresentBuffers ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
#7  0x00000000444c6096 in atio6axx!DrvPresentBuffers ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
#8  0x0000000043b8019b in atio6axx!DrvPresentBuffers ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
#9  0x0000000043f52fd6 in atio6axx!DrvPresentBuffers ()
   from C:\WINDOWS\System32\DriverStore\FileRepository\c0313824.inf_amd64_cff8240637965d03\atio6axx.dll
#10 0x00007ffbb04fd4f4 in SS2OSD!GetHotPatchInfo ()
   from C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\x64\SS2OSD.dll
#11 0x00007ffbb0506d1c in SS2OSD!GetHotPatchInfo ()
   from C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\x64\SS2OSD.dll
#12 0x00007ffbb05073d7 in SS2OSD!GetHotPatchInfo ()
   from C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\x64\SS2OSD.dll
#13 0x00007ffbb0506a9b in SS2OSD!GetHotPatchInfo ()
   from C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\x64\SS2OSD.dll
#14 0x00007ffbb04fd168 in SS2OSD!GetHotPatchInfo ()
   from C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\x64\SS2OSD.dll
#15 0x00007ffbb04f659c in SS2OSD!GetHotPatchInfo ()
   from C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\x64\SS2OSD.dll
#16 0x00007ffbb04f6427 in SS2OSD!GetHotPatchInfo ()
   from C:\Program Files\ASUSTeKcomputer.Inc\SS2\UserInterface\x64\SS2OSD.dll
#17 0x00007ffbc7e8027e in gdi32full!SwapBuffers ()
   from C:\WINDOWS\System32\gdi32full.dll
#18 0x0000000070773cfa in QWindowsOpengl32DLL::swapBuffers (
    this=0x7082e940 <QOpenGLStaticContext::opengl32>, dc=0x1b010f4a)
    at qwindowsglcontext.cpp:206
#19 0x000000007077841e in QWindowsGLContext::swapBuffers (this=0x3678a880,
    surface=0x36697920) at qwindowsglcontext.cpp:1252
#20 0x000000000831b4c0 in QOpenGLContext::swapBuffers (this=0x3678a6f0,
    surface=0x36692460) at kernel/qopenglcontext.cpp:1073
#21 0x000000002426a926 in QSGRenderThread::syncAndRender (this=0x3678a400)
    at scenegraph/qsgthreadedrenderloop.cpp:641
#22 0x000000002426b2bc in QSGRenderThread::run (this=0x3678a400)
    at scenegraph/qsgthreadedrenderloop.cpp:719
#23 0x00000000010ae8fd in QThreadPrivate::start (arg=0x3678a400)
    at thread/qthread_win.cpp:378
#24 0x00007ffbc9702774 in KERNEL32!BaseThreadInitThunk ()
   from C:\WINDOWS\System32\kernel32.dll
#25 0x00007ffbcb900d61 in ntdll!RtlUserThreadStart ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#26 0x0000000000000000 in ?? ()
```

**Comment by aquiles2k** [comment]
Ok, problem was on my side. This wonderfull dll (ASUSTeKcomputer.Inc\SS2\UserInterface\x64\SS2OSD.dll) irritated me and after some research it seems that this sound tool (Sonic Studio 2) installed by my mainboard manufacturer causes all kinds of problems. So after deinstalling it everything is fine now. And Im not getting into why a sound programm should mess with my graphics drivers. Facepalm...
