### ISSUE TITLE
OpenGL renderer: Crash on closing after zooming

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#403]
I get a crash on closing the application after zooming.  I do not see the call stack on crash as helpful, but I assume that asynchronous resources are still running or are accesses, while the application is already closed.

```
#0  p2t::Triangle::EdgeIndex (this=this@entry=0x0, p1=p1@entry=0x7fffb2e789e0, 
    p2=p2@entry=0x7fffb2e78c50)
    at ../libosmscout-map-opengl/src/poly2tri/common/shapes.cc:171
#1  0x00007ffff7bd0551 in p2t::Sweep::IsEdgeSideOfTriangle (
    this=this@entry=0x7fffb2e79560, triangle=..., ep=..., eq=...)
    at ../libosmscout-map-opengl/src/poly2tri/sweep/sweep.cc:164
#2  0x00007ffff7bd1cc9 in p2t::Sweep::EdgeEvent (this=0x7fffb2e79560, 
    tcx=<error reading variable: Cannot access memory at address 0x7fffe26dc710>, ep=..., eq=..., triangle=0x0, point=...)
    at ../libosmscout-map-opengl/src/poly2tri/sweep/sweep.cc:109
#3  0x00007ffff7bd1fa9 in p2t::Sweep::EdgeEvent (this=0x7fffb2e79560, 
    tcx=<error reading variable: Cannot access memory at address 0x7fffe26dc770>, ep=..., eq=..., triangle=0x7fffb2e7db60, point=...)
    at ../libosmscout-map-opengl/src/poly2tri/sweep/sweep.cc:122
#4  0x00007ffff7bd1f50 in p2t::Sweep::EdgeEvent (this=0x7fffb2e79560, tcx=..., 
    ep=..., eq=..., triangle=0x7fffb2e7d780, point=...)
    at ../libosmscout-map-opengl/src/poly2tri/sweep/sweep.cc:139
#5  0x00007ffff7bd1ee1 in p2t::Sweep::EdgeEvent (this=0x7fffb2e79560, 
    tcx=<error reading variable: Cannot access memory at address 0x7fffe26dc830>, ep=..., eq=..., triangle=0x7fffb2e7d710, point=...)
    at ../libosmscout-map-opengl/src/poly2tri/sweep/sweep.cc:155
#6  0x00007ffff7bd1fa9 in p2t::Sweep::EdgeEvent (this=0x7fffb2e79560, 
    tcx=<error reading variable: Cannot access memory at address 0x7fffe26dc890>, ep=..., eq=..., triangle=0x7fffb2e7d780, point=...)
    at ../libosmscout-map-opengl/src/poly2tri/sweep/sweep.cc:122
#7  0x00007ffff7bd1fa9 in p2t::Sweep::EdgeEvent (this=0x7fffb2e79560, 
    tcx=<error reading variable: Cannot access memory at address 0x7fffe26dc8f0>, ep=..., eq=..., triangle=0x7fffb2e7db60, point=...)
    at ../libosmscout-map-opengl/src/poly2tri/sweep/sweep.cc:122
#8  0x00007ffff7bd20c2 in p2t::Sweep::SweepPoints (
    this=this@entry=0x7fffb2e79560, tcx=...)
    at ../libosmscout-map-opengl/src/poly2tri/sweep/sweep.cc:56
#9  0x00007ffff7bd21d7 in p2t::Sweep::Triangulate (this=0x7fffb2e79560, 
    tcx=...) at ../libosmscout-map-opengl/src/poly2tri/sweep/sweep.cc:45
#10 0x00007ffff7bcf9ef in p2t::CDT::Triangulate (
    this=this@entry=0x7fffb2e77a40)
    at ../libosmscout-map-opengl/src/poly2tri/sweep/cdt.cc:52
#11 0x00007ffff7bcf342 in osmscout::Triangulate::TriangulateWithHoles (
    points=<error reading variable: Cannot access memory at address 0x7fffe26dcc30>) at ../libosmscout-map-opengl/src/osmscout/Triangulate.cpp:67
#12 0x00007ffff7bcb846 in osmscout::MapPainterOpenGL::ProcessAreaData (
    this=this@entry=0xf1ac90, data=..., parameter=..., projection=..., 
    styleConfig=<error reading variable: Cannot access memory at address 0x60a9f8>, BoundingBox=...)
    at ../libosmscout-map-opengl/src/osmscout/MapPainterOpenGL.cpp:312
#13 0x00007ffff7bcbde8 in osmscout::MapPainterOpenGL::loadData (this=0xf1ac90, 
    data=..., parameter=..., projection=..., 
    styleConfig=<error reading variable: Cannot access memory at address 0x60a9f8>, BoundingBox=...)
    at ../libosmscout-map-opengl/src/osmscout/MapPainterOpenGL.cpp:105
#14 0x00000000004055c6 in LoadData ()
    at ../OSMScoutOpenGL/src/OSMScoutOpenGL.cpp:69
#15 0x000000000040576a in std::__invoke_impl<bool, bool (*)()> (
    __f=<optimized out>) at /usr/include/c++/7.1.1/bits/invoke.h:60
#16 std::__invoke<bool (*)()> (__fn=<optimized out>)
    at /usr/include/c++/7.1.1/bits/invoke.h:96
#17 std::thread::_Invoker<std::tuple<bool (*)()> >::_M_invoke<0ul> (
    this=<optimized out>) at /usr/include/c++/7.1.1/thread:234
#18 std::thread::_Invoker<std::tuple<bool (*)()> >::operator() (
    this=<optimized out>) at /usr/include/c++/7.1.1/thread:243
#19 std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<bool>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<bool (*)()> >, bool>::operator() (this=0x7fffe26dce20)
---Type <return> to continue, or q <return> to quit---
    at /usr/include/c++/7.1.1/future:1338
#20 std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<bool>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<bool (*)()> >, bool> >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/include/c++/7.1.1/bits/std_function.h:302
#21 0x000000000040582b in std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>::operator()() const (
    this=<optimized out>) at /usr/include/c++/7.1.1/bits/std_function.h:706
#22 std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (this=0x2773be0, __f=<optimized out>, __did_set=0x7fffe26dcdc7)
    at /usr/include/c++/7.1.1/future:542
```

**Comment by Framstag** [comment]
Does work now without a problem.
